[package]
name = "kubab1610/statbat"
version = "0.1.0"
description = "StatBat cricket website"

[[command]]
name = "start"
module = "wasmer/node:node"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["server.js"]

[fs]
"/app" = "."
